version: '3.7'
services:
    postgres:
        image: postgis/postgis:14-3.3
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5433:5432'
